language: node_js
node_js: stable
branches:
  only:
    - master
cache:
  apt: true
  npm: true
  directories:
    - node_modules
install:
  - npm i yarn -g
  - yarn install
jobs:
  include:
    - stage: test
      script:
        - yarn build
        - yarn test
      after_success:
        - yarn test --coverage
        - cat ./coverage/lcov.info | yarn coveralls
    - stage: deploy
      if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_KEY"
